--- 
title: "Estadística Aplicada III"
author: "Andreu Boada de Atela"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: andreuboada/est-aplicada-3-2018
description: "Notas y material para el curso de Estadística Aplicada III, 2018 (ITAM)"
---

# Temario y referencias {-}

**Todas las notas y material del curso estarán en este** [repositorio](https://github.com/andreuboada/est-aplicada-3-2018).

- Análisis exploratorio de datos
- Análisis de datos categórica
- Análisis de conglomerados: clustering jerárquico, k-medias
- Componentes principales
- Análisis de factores
- Análisis canónico
- Análisis discriminante
- Regresión logística 
- Regularización y selección de modelos
- Introducción a la estadística espacial


### Evaluación {-}

- Tareas semanales (20%)
- Examen parcial (30% práctico, 20% teórico)
- Un examen final (30% práctico)

### Software: R y Rstudio {-}

- [R](https://cran.r-project.org) Sitio de R (CRAN)
- [Rstudio](https://www.rstudio.com/products/RStudio/) Interfaz gráfica para trabajar en R.
- [Recursos para aprender R](https://www.rstudio.com/online-learning/#R)

### Referencia principal {-}

- [Johnson, R., y Wichern, D. Applied multivariate statistical analysis. Upper Saddle River, N. J.: Pearson Prentice Hall, 2007.](https://www.pearson.com/us/higher-education/program/Johnson-Applied-Multivariate-Statistical-Analysis-6th-Edition/PGM274834.html)

### Otras referencias {-}

- [Pattern Recognition and Machine Learning](http://www.springer.com/us/book/9780387310732)

- [The Elements of Statistical Learning, Hastie, Tibshirani y Friedman](https://web.stanford.edu/~hastie/ElemStatLearn/)

- Agresti, Alan. Categorical data analysis. 3rd ed.  Hoboken, N. J.: John Wiley & Sons, 2013.

- Greenacre, Michael J., ed. Multiple correspondence analysis and related methods. Boca Raton, Fla.: Chapman & Hall/CRC, 2006
 
- Thompson, Bruce. Canonical correlation analysis : uses and interpretation. Thousand Oaks, Calif.: Sage Publications, 1984

- Jackson, J. Edward. A user’s guide to principal components. New York: John Wiley & Sons, 1991.

- Harrell, Frank E. Regression modeling strategies : with applications to linear models, logistic regression, and survival analysis. New York: Springer, c2001.

- McLachlan, Geoffrey J. Discriminant analysis and statistical pattern recognition. New York: John Wiley & Sons, 1992. 

### Tareas {-}

Enviar tareas por correo electrónico a: [andreuboada@gmail.com](andreuboada@gmail.com) con el asunto "EAPLICADA3-Tarea-[XX]-[clave única 1]-[clave única 2]" donde [XX] es el número de la tarea, [clave única 1] y [clave única 2] son tu clave y la de tu compañero con quien vas a trabajar durante el semestre.
